# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='details',
            field=models.TextField(),
        ),
    ]
